/**
 * DO NOT EDIT THIS FILE!
 */
package csc2a.pta.model;

import javafx.geometry.Point2D;

/**
 * Abstract base class of all Anomalies
 * 
 * DO NOT EDIT THIS FILE!
 * 
 * @author Mr. Greaves
 *
 */
public abstract class Anomaly implements IProbable
{
	private Point2D			location;
	private EAnomalyType	type;

	/**
	 * Create a new Anomaly instance.
	 * @param x X position of the Anomaly
	 * @param y Y position of the Anomaly
	 * @param type Anomaly type of the Anomaly
	 */
	public Anomaly(int x, int y, EAnomalyType type)
	{
		this.location = new Point2D(x, y);
		this.setType(type);
	}

	/**
	 * @return the location
	 */
	public Point2D getLocation()
	{
		return location;
	}

	/**
	 * @param location
	 *          the location to set
	 */
	public void setLocation(Point2D location)
	{
		this.location = location;
	}

	/**
	 * @return the type
	 */
	public EAnomalyType getType()
	{
		return type;
	}

	/**
	 * @param type
	 *          the type to set
	 */
	public void setType(EAnomalyType type)
	{
		this.type = type;
	}
}
/**
 * DO NOT EDIT THIS FILE!
 */
