/**
 * DO NOT EDIT THIS FILE!
 */
package csc2a.pta.model;

import java.awt.Color;

/**
 * Anomaly type enumeration
 *
 * DO NOT EDIT THIS FILE!
 * 
 * @author Mr. Greaves
 */
public enum EAnomalyType
{
	GEOLOGICAL(Color.GREEN), 
	GRAVITATIONAL(Color.YELLOW), 
	SPATIAL(Color.CYAN), 
	TEMPORAL(Color.MAGENTA);

	private final java.awt.Color anomalyColour;

	private EAnomalyType(java.awt.Color colour)
	{
		anomalyColour = colour;
	}

	public java.awt.Color getAnomalyColour()
	{
		return anomalyColour;
	}
}
/**
 * DO NOT EDIT THIS FILE!
 */
